// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
///await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnSjNNnuEqhFzuQmfCHfa0quLsSUFeEk0',
    appId: '1:827612041429:web:981ecf0d8059f1f840925c',
    messagingSenderId: '827612041429',
    projectId: 'cuts-and-curls-38cb9',
    authDomain: 'cuts-and-curls-38cb9.firebaseapp.com',
    storageBucket: 'cuts-and-curls-38cb9.firebasestorage.app',
    measurementId: 'G-HJFKL4N9SL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZVVfLPBrviDWyYX6hAszehmxXxSSJwiU',
    appId: '1:827612041429:android:ff1d96c81a7cf2b340925c',
    messagingSenderId: '827612041429',
    projectId: 'cuts-and-curls-38cb9',
    storageBucket: 'cuts-and-curls-38cb9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOECYbSQKZ7A_-bNmOQuUEct0QkkORvVI',
    appId: '1:827612041429:ios:ce4b03101c6324e740925c',
    messagingSenderId: '827612041429',
    projectId: 'cuts-and-curls-38cb9',
    storageBucket: 'cuts-and-curls-38cb9.firebasestorage.app',
    iosBundleId: 'com.example.cutsAndCurls',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOECYbSQKZ7A_-bNmOQuUEct0QkkORvVI',
    appId: '1:827612041429:ios:ce4b03101c6324e740925c',
    messagingSenderId: '827612041429',
    projectId: 'cuts-and-curls-38cb9',
    storageBucket: 'cuts-and-curls-38cb9.firebasestorage.app',
    iosBundleId: 'com.example.cutsAndCurls',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnSjNNnuEqhFzuQmfCHfa0quLsSUFeEk0',
    appId: '1:827612041429:web:5eec994dae452adb40925c',
    messagingSenderId: '827612041429',
    projectId: 'cuts-and-curls-38cb9',
    authDomain: 'cuts-and-curls-38cb9.firebaseapp.com',
    storageBucket: 'cuts-and-curls-38cb9.firebasestorage.app',
    measurementId: 'G-XFN3YNRWQ2',
  );

}