// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7kLUBIkloQVAQnApY8TnhJQYh_4RUeAQ',
    appId: '1:627376610013:android:7f0404a9513fe286f41934',
    messagingSenderId: '627376610013',
    projectId: 'sheersync',
    storageBucket: 'sheersync.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE0S2dcBrPZNpXLa4eP_tX_e9M7p2NNTA',
    appId: '1:627376610013:ios:05dc5eab416d9400f41934',
    messagingSenderId: '627376610013',
    projectId: 'sheersync',
    storageBucket: 'sheersync.firebasestorage.app',
    iosBundleId: 'com.example.sheersync',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi1jg_iV-4a0KJa4sNrHOIm940Jt0yAA4',
    appId: '1:627376610013:web:59bf219b9a4d3009f41934',
    messagingSenderId: '627376610013',
    projectId: 'sheersync',
    authDomain: 'sheersync.firebaseapp.com',
    storageBucket: 'sheersync.firebasestorage.app',
    measurementId: 'G-2VV6TG3N5Q',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE0S2dcBrPZNpXLa4eP_tX_e9M7p2NNTA',
    appId: '1:627376610013:ios:05dc5eab416d9400f41934',
    messagingSenderId: '627376610013',
    projectId: 'sheersync',
    storageBucket: 'sheersync.firebasestorage.app',
    iosBundleId: 'com.example.sheersync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAi1jg_iV-4a0KJa4sNrHOIm940Jt0yAA4',
    appId: '1:627376610013:web:8829f6f8a50b13aef41934',
    messagingSenderId: '627376610013',
    projectId: 'sheersync',
    authDomain: 'sheersync.firebaseapp.com',
    storageBucket: 'sheersync.firebasestorage.app',
    measurementId: 'G-M1XXN1PH53',
  );

}