// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwe86-O2czzdCT3HVs4sFpNxHC3KXyb7U',
    appId: '1:818917916817:web:d4f536596fffe683c73f30',
    messagingSenderId: '818917916817',
    projectId: 'cutscurls',
    authDomain: 'cutscurls.firebaseapp.com',
    storageBucket: 'cutscurls.firebasestorage.app',
    measurementId: 'G-2BXKVS1HZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoRcrA1YDH5TDm3ZNVALFTuQCsVKHMHaU',
    appId: '1:818917916817:android:5f4d045a82672349c73f30',
    messagingSenderId: '818917916817',
    projectId: 'cutscurls',
    storageBucket: 'cutscurls.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyJKKPwI6WTAMcUjaWOGcnpwB5TNhvQ6I',
    appId: '1:818917916817:ios:6765494af850ef21c73f30',
    messagingSenderId: '818917916817',
    projectId: 'cutscurls',
    storageBucket: 'cutscurls.firebasestorage.app',
    iosBundleId: 'com.hair.cutscurls',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyJKKPwI6WTAMcUjaWOGcnpwB5TNhvQ6I',
    appId: '1:818917916817:ios:6765494af850ef21c73f30',
    messagingSenderId: '818917916817',
    projectId: 'cutscurls',
    storageBucket: 'cutscurls.firebasestorage.app',
    iosBundleId: 'com.hair.cutscurls',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwe86-O2czzdCT3HVs4sFpNxHC3KXyb7U',
    appId: '1:818917916817:web:e2d18c86ac17ae7fc73f30',
    messagingSenderId: '818917916817',
    projectId: 'cutscurls',
    authDomain: 'cutscurls.firebaseapp.com',
    storageBucket: 'cutscurls.firebasestorage.app',
    measurementId: 'G-RVNFLJNWFW',
  );
}
